name: date_planner
description: "An iOS-style date planner."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  intl: null
  provider: null
  shadcn_ui: ^0.24.0
  uuid: null

dev_dependencies:
  flutter_lints: ^5.0.0
